### ISSUE TITLE
Problem trying to move a chat window inside Raptor

### ISSUE THREAD

**Issue by Eskatrem** [Raptor-Fics-Interface/Raptor#24]
(Running it on debian 64)

Error in execute
IllegalArgumentException: Argument not valid
java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.removeTabControl(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.setTopRight(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.setTopRight(Unknown Source)
	at raptor.RaptorWindow$RaptorTabFolder.updateToolbar(RaptorWindow.java:304)
	at raptor.RaptorWindow$RaptorTabItem$1$1.execute(RaptorWindow.java:476)
	at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at raptor.Raptor.main(Raptor.java:236)

**Comment by cday-fics** [comment]
Which version were you using? I disabled moving tabs between tab folders in rc4.

**Comment by cday-fics** [comment]
Turns out this was happening in 1.0 beta. Closing the issue.
