### ISSUE TITLE
Error parsing PGN (Could be a problem with the bitboard move validation)

### ISSUE THREAD

**Issue by cday-fics** [Raptor-Fics-Interface/Raptor#25]
Event "1 0 rated private lightning"]
[Site "freechess.org"]
[Date "2014.05.10"]
[Round "?"]
[White "cday"]
[Black "Vukvolan"]
[Result "0-1"]
[ResultDescription "cday forfeits on time"]
[WhiteElo "1735"]
[BlackElo "1581"]
[PlyCount "86"]
[Variant "lightning"]
[TimeControl "60+0"]
[WhiteClock "00:01:00.0"]
[BlackClock "00:01:00.0"]
[WhiteLagMillis "13483"]
[BlackLagMillis "11029"]
[WhiteRemainingMillis "-783"]
[BlackRemainingMillis "9520"]
[WhiteOnTop "0"]

1. e4 {[%emt 0.000]} e5 {[%emt 0.000]} 2. f4 {[%emt 1.120]} d5 {[%emt 0.100]} 3. exd5 {[%emt 1.219]}
e4 {[%emt 0.518]} 4. d3 {[%emt 1.447]} f5 {[%emt 0.100]} 5. Nc3 {[%emt 3.496]} Bd6 {[%emt 0.974]}
6. dxe4 {[%emt 2.088]} fxe4 {[%emt 0.499]} 7. Nxe4 {[%emt 0.573]} Qe7 {[%emt 0.437]}
8. Bd3 {[%emt 0.731]} Nf6 {[%emt 0.817]} 9. Qe2 {[%emt 1.993]} Nxe4 {[%emt 1.023]}
10. Qxe4 {[%emt 1.319]} Qxe4+ {[%emt 1.545]} 11. Bxe4 {[%emt 1.692]} O-O {[%emt 0.381]}
12. Nf3 {[%emt 3.829]} Bf5 {[%emt 1.102]} 13. Bxf5 {[%emt 1.713]} Rxf5 {[%emt 0.756]}
14. O-O {[%emt 0.665]} h6 {[%emt 0.763]} 15. Nd4 {[%emt 1.997]} Rf8 {[%emt 1.785]}
16. Ne6 {[%emt 1.588]} Re8 {[%emt 0.720]} 17. Bd2 {[%emt 1.189]} Nd7 {[%emt 0.947]}
18. Bc3 {[%emt 0.726]} Nc5 {[%emt 4.797]} 19. Nxg7 {[%emt 1.665]} Re4 {[%emt 5.432]}
20. Nf5 {[%emt 1.445]} Rxf4 {[%emt 2.607]} 21. Nxd6 {[%emt 1.526]} Rxf1+ {[%emt 1.931]}
22. Rxf1 {[%emt 0.100]} cxd6 {[%emt 0.705]} 23. Rf6 {[%emt 0.689]} Ne4 {[%emt 1.355]}
24. Rxh6 {[%emt 1.095]} Kf7 {[%emt 0.363]} 25. Rh7+ {[%emt 2.445]} Kg6 {[%emt 1.626]}
26. Rxb7 {[%emt 0.446]} Nxc3 {[%emt 1.332]} 27. bxc3 {[%emt 1.023]} Kf5 {[%emt 0.588]}
28. c4 {[%emt 2.292]} Ke5 {[%emt 0.628]} 29. Rc7 {[%emt 0.799]} Rb8 {[%emt 1.471]}
30. Rxa7 {[%emt 1.552]} Rb1+ {[%emt 1.436]} 31. Kf2 {[%emt 1.136]} Rb2 {[%emt 0.478]}
32. Kf3 {[%emt 0.992]} Rxc2 {[%emt 0.501]} 33. Rc7 {[%emt 1.048]} Rxa2 {[%emt 1.306]}
34. h4 {[%emt 3.008]} Ra3+ {[%emt 0.509]} 35. Kg4 {[%emt 1.087]} Ra2 {[%emt 1.878]}
36. g3 {[%emt 0.792]} Re2 {[%emt 1.365]} 37. h5 {[%emt 0.771]} Rh2 {[%emt 1.718]}
38. Re7+ {[%emt 2.504]} Kd4 {[%emt 1.178]} 39. Re6 {[%emt 0.297]} Kxc4 {[%emt 1.283]}
40. Rxd6 {[%emt 0.565]} Kc5 {[%emt 0.383]} 41. Rd8 {[%emt 3.113]} Rh1 {[%emt 1.844]}
42. d6 {[%emt 0.723]} Kc6 {[%emt 0.835]} 43. d7 {[%emt 0.522]} 44. Rg8 0-1

16:09:31,548 ERROR LenientPgnParserListener:40 - Invalid move encountered
java.lang.IllegalArgumentException: Invalid move Rg8
 emptyBB            occupiedBB         notColorToMoveBB   color[WHITE]       color[BLACK]      
 1 1 1 0 1 1 1 1    0 0 0 1 0 0 0 0    1 1 1 1 1 1 1 1    0 0 0 1 0 0 0 0    0 0 0 0 0 0 0 0   
 1 1 1 0 1 1 1 1    0 0 0 1 0 0 0 0    1 1 1 1 1 1 1 1    0 0 0 1 0 0 0 0    0 0 0 0 0 0 0 0   
 1 1 0 1 1 1 1 1    0 0 1 0 0 0 0 0    1 1 0 1 1 1 1 1    0 0 0 0 0 0 0 0    0 0 1 0 0 0 0 0   
 1 1 1 1 1 1 1 0    0 0 0 0 0 0 0 1    1 1 1 1 1 1 1 1    0 0 0 0 0 0 0 1    0 0 0 0 0 0 0 0   
 1 1 1 1 1 1 0 1    0 0 0 0 0 0 1 0    1 1 1 1 1 1 1 1    0 0 0 0 0 0 1 0    0 0 0 0 0 0 0 0   
 1 1 1 1 1 1 0 1    0 0 0 0 0 0 1 0    1 1 1 1 1 1 1 1    0 0 0 0 0 0 1 0    0 0 0 0 0 0 0 0   
 1 1 1 1 1 1 1 1    0 0 0 0 0 0 0 0    1 1 1 1 1 1 1 1    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 1 1 1 1 1 1 1 0    0 0 0 0 0 0 0 1    1 1 1 1 1 1 1 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 1   

 [WHITE][PAWN]      [WHITE][KNIGHT]    [WHITE][BISHOP]    [WHITE][ROOK]      [WHITE][QUEEN]     [WHITE][KING]     
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 1 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 1 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 1    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 1 0   
 0 0 0 0 0 0 1 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   

 [BLACK][PAWN]      [BLACK][KNIGHT]    [BLACK][BISHOP]    [BLACK][ROOK]      [BLACK][QUEEN]     [BLACK][KING]     
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 1 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   
 0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 1    0 0 0 0 0 0 0 0    0 0 0 0 0 0 0 0   

|*|*|*|R|*|*|*|*|   To Move: Black Last Move: d7
|*|*|*|P|*|*|*|*|   Piece counts [WP=3 WN=0 WB=0 WR=1 WQ=0 WK=1][BP=0 BN= 0 BB=0 BR=1 BQ=0 BK=1]
|*|*|k|*|*|*|*|*|   Moves: 85 EP: - Castle: -
|*|*|*|*|*|*|*|P|   FEN: 3R4/3P4/2k5/7P/6K1/6P1/8/7r b - - 0 43
|*|*|*|*|*|*|K|*|   State: 3072 Variant=lightning Result=0-1
|*|*|*|*|*|*|P|*|   Event: 1 0 rated private lightning Site=freechess.org Date=2014.05.10
|*|*|*|*|*|*|*|*|   WhiteName: cday BlackName=Vukvolan WhiteTime=-783 whiteLag=13483 blackRemainingTImeMillis = 9520 blackLag=11029
|*|*|*|*|*|*|*|r|   initialWhiteClock: 00:01:00.0 initialBlackClocks=00:01:00.0

Legals=[Ra1, Rb1, Rc1, Rd1, Re1, Rf1, Rg1, Rh2, Rh3, Rh4, Kb5, Kc5, Kd5, Kb6,
Kd6, Kb7, Kc7, Rxh5]
Movelist=[e4, e5, f4, d5, exd5, e4, d3, f5, Nc3, Bd6, dxe4, fxe4, Nxe4, Qe7,
Bd3, Nf6, Qe2, Nxe4, Qxe4, Qxe4+, Bxe4, O-O, Nf3, Bf5, Bxf5, Rxf5, O-O, h6, Nd4,
Rf8, Ne6, Re8, Bd2, Nd7, Bc3, Nc5, Nxg7, Re4, Nf5, Rxf4, Nxd6, Rxf1+, Rxf1,
cxd6, Rf6, Ne4, Rxh6, Kf7, Rh7+, Kg6, Rxb7, Nxc3, bxc3, Kf5, c4, Ke5, Rc7, Rb8,
Rxa7, Rb1+, Kf2, Rb2, Kf3, Rxc2, Rc7, Rxa2, h4, Ra3+, Kg4, Ra2, g3, Re2, h5,
Rh2, Re7+, Kd4, Re6, Kxc4, Rxd6, Kc5, Rd8, Rh1, d6, Kc6, d7]
Squares with promote masks: []
	at raptor.chess.ClassicGame.testForSanDisambiguationFromCheck(ClassicGame.java:2429)
	at raptor.chess.ClassicGame.makeSanMove(ClassicGame.java:980)
	at raptor.chess.pgn.LenientPgnParserListener.makeGameMoveFromWord(LenientPgnParserListener.java:591)
	at raptor.chess.pgn.LenientPgnParserListener.onMoveWord(LenientPgnParserListener.java:404)
	at raptor.chess.pgn.AbstractPgnParser.fireMoveWord(AbstractPgnParser.java:82)
	at raptor.chess.pgn.SimplePgnParser.parse(SimplePgnParser.java:267)
	at raptor.swt.PgnProcessingDialog$1.run(PgnProcessingDialog.java:166)
	at raptor.service.ThreadService$RunnableExceptionDecorator.run(ThreadService.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by cday-fics** [comment]
Turns out the move rg8 was actually invalid. For some reason raptor wrote this bad move to the pgn file. It has happened in 1 out of 3800+ games.

**Comment by cday-fics** [comment]
This is minor so I am not worrying about it for the 1.0 release.
