### ISSUE TITLE
Error playing sounds on startup on windows 10

### ISSUE THREAD

**Issue by benfranklin79** [Raptor-Fics-Interface/Raptor#41]
I received the following in the Raptor Error dialog when starting up the application for the first time on windows 10

```
Error playing sound resources/sounds/alert.wav
IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED unknown sample rate, 16 bit, stereo, 4 bytes/frame, big-endian is supported.
java.lang.IllegalArgumentException: No line matching interface Clip supporting format PCM_SIGNED unknown sample rate, 16 bit, stereo, 4 bytes/frame, big-endian is supported.
	at javax.sound.sampled.AudioSystem.getLine(Unknown Source)
	at javax.sound.sampled.AudioSystem.getClip(Unknown Source)
	at raptor.sound.JavaxSampledSoundPlayer.play(JavaxSampledSoundPlayer.java:70)
	at raptor.sound.JavaxSampledSoundPlayer.playSound(JavaxSampledSoundPlayer.java:114)
	at raptor.service.SoundService$3.run(SoundService.java:152)
	at raptor.service.ThreadService$RunnableExceptionDecorator.run(ThreadService.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Here is some information about my operating system:

![image](https://cloud.githubusercontent.com/assets/3197935/15039454/39ec9ba8-12a5-11e6-9b56-51a2cebd3cc5.png)

**Comment by cday-fics** [comment]
Looks like I need to find an alternative way of playing sounds in windows 10 its different from 7 and 8. I will take a look at it.

**Comment by cday-fics** [comment]
Does this happen on all sounds or just alert.wav?
