### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ZnBangash** [Raptor-Fics-Interface/Raptor#43]
Error occured! We are trying to make Raptor bug free and we need your help! Please take a moment to report this issue by selecting the menu:
  Help -> Report Issue 

Error in execute
SWTException: Widget is disposed
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source)
	at org.eclipse.swt.widgets.Composite.layout(Unknown Source)
	at raptor.swt.chat.ChatConsole.setPingTime(ChatConsole.java:197)
	at raptor.swt.chat.ChatConsoleController$2$1.execute(ChatConsoleController.java:154)
	at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at raptor.Raptor.main(Raptor.java:214)

**Comment by cday-fics** [comment]
Thanks for posting this I will fix it in the next release.

**Comment by fractalguy1974** [comment]
I hit the same exception but with a slightly different stack:

Error in execute
SWTException: Widget is disposed
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source)
	at org.eclipse.swt.widgets.Control.isVisible(Unknown Source)
	at raptor.swt.chess.analysis.UciAnalysisWidget$10$1.execute(UciAnalysisWidget.java:486)
	at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at raptor.Raptor.main(Raptor.java:214)
