### ISSUE TITLE
Crash when opening seek window

### ISSUE THREAD

**Issue by marcus233** [Raptor-Fics-Interface/Raptor#50]
I'm using Ubuntu 16.04, OpenJDK 9 JRE, and Raptor 1.0

When I connect to FICS (as a guest) and open the Seek tab Raptor chess disconnects from FICS with the following error:

at raptor.connector.ics.IcsConnector.parseMessage(IcsConnector.java:1873) 	at raptor.connector.ics.IcsConnector.messageArrived(IcsConnector.java:1771) 	at raptor.connector.ics.timeseal.TimesealSocketMessageProducer.messageLoop(TimesealSocketMessageProducer.java:219) 	at raptor.connector.ics.timeseal.TimesealSocketMessageProducer$1.run(TimesealSocketMessageProducer.java:286) 	at java.lang.Thread.run(java.base@9-internal/Thread.java:804) Caused by: java.lang.NumberFormatException: For input string: "and" 	at java.lang.NumberFormatException.forInputString(java.base@9-internal/NumberFormatException.java:65) 	at java.lang.Integer.parseInt(java.base@9-internal/Integer.java:695) 	at java.lang.Integer.parseInt(java.base@9-internal/Integer.java:813) 	at raptor.connector.ics.SoughtParser.parse(SoughtParser.java:104) 	at raptor.connector.ics.IcsParser.processSought(IcsParser.java:1161) 	at raptor.connector.ics.IcsParser.parse(IcsParser.java:238) 	at raptor.connector.ics.IcsConnector.parseMessage(IcsConnector.java:1861) 	... 4 more Disconnected

**Comment by marcus233** [comment]
This is caused by the setting "Seek output type" being set to "show formula filtered seeks" -- changing this to "show all seeks" fixes the problem.
