### ISSUE TITLE
Error in execute

### ISSUE THREAD

**Issue by sojuzpl** [Raptor-Fics-Interface/Raptor#56]
I copied report from Raptor Error menu - MacOS X 10.11.6, Raptor 1.0

Error in execute
SWTException: Widget is disposed
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source)
	at org.eclipse.swt.widgets.Composite.layout(Unknown Source)
	at raptor.swt.chat.ChatConsole.setPingTime(ChatConsole.java:197)
	at raptor.swt.chat.ChatConsoleController$2$1.execute(ChatConsoleController.java:154)
	at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at raptor.Raptor.main(Raptor.java:214)

**Comment by lancent100** [comment]
This should be fixed with commit 257dc272f94b4ecd978c7f6bea9e8e7cb184d49d from 4 June by cday-fics
