### ISSUE TITLE
Raptor on Mac OS Sierra

### ISSUE THREAD

**Issue by edudemy** [Raptor-Fics-Interface/Raptor#61]
FICS Connect button is greyed out? Is this a known bug. It was working earlier.Can see the console window and the browser opens up the github page.

**Comment by edudemy** [comment]
Attaching Error log:

Error occured! We are trying to make Raptor bug free and we need your help! Please take a moment to report this issue by selecting the menu:
  Help -> Report Issue 

Error reading file: /Applications/Raptor_v98u3f5/Raptor.app/Contents/MacOS/bsd-new-license.html
FileNotFoundException: bsd-new-license.html (No such file or directory)
java.io.FileNotFoundException: bsd-new-license.html (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileReader.<init>(FileReader.java:72)
	at raptor.util.FileUtils.fileAsString(Unknown Source)
	at raptor.RaptorWindow$30.run(Unknown Source)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
	at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:583)
	at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:500)
	at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at raptor.Raptor.main(Unknown Source)
