### ISSUE TITLE
Error in ThreadService Runnable

### ISSUE THREAD

**Issue by dirtygardner** [Raptor-Fics-Interface/Raptor#67]
Error in ThreadService Runnable.
NullPointerException: 
java.lang.NullPointerException
	at raptor.chess.pgn.PgnUtils.getMove(PgnUtils.java:156)
	at raptor.chess.ClassicGame.toPgn(ClassicGame.java:1328)
	at raptor.chess.pgn.PgnUtils.appendGameToFile(PgnUtils.java:92)
	at raptor.swt.chess.controller.PlayingController$2$2$1.run(PlayingController.java:164)
	at raptor.service.ThreadService$RunnableExceptionDecorator.run(ThreadService.java:49)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
	at java.util.concurrent.FutureTask.run(FutureTask.java:166)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:292)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
	at java.lang.Thread.run(Thread.java:722)

**Comment by pendalino** [comment]
Me too-

Error occured! We are trying to make Raptor bug free and we need your help! Please take a moment to report this issue by selecting the menu:
  Help -> Report Issue 

Error in ThreadService Runnable.
NullPointerException: 
java.lang.NullPointerException
	at raptor.connector.fics.FicsConnector.showLoginDialog(FicsConnector.java:377)
	at raptor.Raptor$2.run(Raptor.java:172)
	at raptor.service.ThreadService$RunnableExceptionDecorator.run(ThreadService.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
