### ISSUE TITLE
Widget is disposed

### ISSUE THREAD

**Issue by pragathoys** [Raptor-Fics-Interface/Raptor#69]
Error in execute
SWTException: Widget is disposed
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source)
	at org.eclipse.swt.widgets.Control.isVisible(Unknown Source)
	at raptor.swt.chess.analysis.UciAnalysisWidget$10$1.execute(UciAnalysisWidget.java:486)
	at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at raptor.Raptor.main(Raptor.java:214)

**Comment by pragathoys** [comment]
I use Ubuntu 14.04 LTS

**Comment by skquinn** [comment]
Also happens on Ubuntu 16.04 LTS. Tends to happen when I close a bunch of channel tabs at once but I've had it happen after just closing one or two.

**Comment by pendalino** [comment]
Here’s mine, when I closed an examiend game

Error in execute
SWTException: Widget is disposed
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.error(Unknown Source)
	at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source)
	at org.eclipse.swt.widgets.Button.setText(Unknown Source)
	at raptor.swt.chess.analysis.UciAnalysisWidget$10$1.execute(UciAnalysisWidget.java:406)
	at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at raptor.Raptor.main(Raptor.java:236)
