### ISSUE TITLE
Problems on Mojave

### ISSUE THREAD

**Issue by fncll** [Raptor-Fics-Interface/Raptor#85]
Removing the -d64 line in the `raptor` startup script at least allowed Raptor to start at all, but it dies with the error:

```
Error occured! We are trying to make Raptor bug free and we need your help! Please take a moment to report this issue by selecting the menu:
  Help -> Report Issue 

Error in execute
NullPointerException: 
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.updateItems(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.updateItems(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.onResize(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder$1.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Control.resized(Unknown Source)
	at org.eclipse.swt.widgets.Composite.resized(Unknown Source)
	at org.eclipse.swt.widgets.Control.setFrameSize(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSView.setFrame(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.custom.SashFormLayout.layout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.updateLayout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.resized(Unknown Source)
	at org.eclipse.swt.widgets.Control.setFrameSize(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSView.setFrame(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.custom.SashFormLayout.layout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.updateLayout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.layout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.layout(Unknown Source)
	at raptor.RaptorWindow$RaptorWindowSashForm.layout(RaptorWindow.java:527)
	at org.eclipse.swt.custom.SashForm.setMaximizedControl(Unknown Source)
	at raptor.RaptorWindow$RaptorWindowSashForm.restore(RaptorWindow.java:581)
	at raptor.RaptorWindow.restoreFolders(RaptorWindow.java:2283)
	at raptor.RaptorWindow$2.execute(RaptorWindow.java:699)
	at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at raptor.Raptor.main(Raptor.java:214)
```

For info, java version:

```
java 13.0.1 2019-10-15
Java(TM) SE Runtime Environment (build 13.0.1+9)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.1+9, mixed mode, sharing)
```

Does Raptor run on Mojave?

**Comment by pendalino** [comment]
I’m running Raptor 1.0 on Mojave 10.14.6 without problems or modifications.
MacBook Pro 2018 and MacBook Pro mid 2012.
I did have problems after a Mojave (10.14..5 or 10.14.6) update on the 2012 MacBook Pro, as well as other programs,  but a OS reinstall solved that.

**Comment by fncll** [comment]
Well, I am not having any other system issues and haven't done anything in particular with Java. Are you running Java 13?

**Comment by pendalino** [comment]
Java Web Start 15.0.1 from 2/22/2019

I have had a lot more problems with Raptor after Java updates in past years.

Good luck

**Comment by fncll** [comment]
OK, thanks for checking. I'll probably give up on Raptor unless someone else has suggestions. Maybe the developer, though it looks like this project might be dead. For the record, I am using xboard for osx to connect to FICS For now. Not as featureful but it does work!

**Comment by carson-day** [comment]
Try this:
https://github.com/Raptor-Fics-Interface/Raptor/issues/81
