### ISSUE TITLE
Raptor not opening in OS 10.15.2 Catalina

### ISSUE THREAD

**Issue by pendalino** [Raptor-Fics-Interface/Raptor#86]
After a recent upgrade of Mac OS to 10.15.2 Catalina from Mojave I ran into problems opening Raptor. Initially I got an error message about the command line tool needed similar to previous OS upgrades (Sierra, Mojave)and posts here. I've upgraded to latest JRE and JDK. Now Raptor won't even open or give an error message.

**Comment by MarinosK** [comment]
I have the same issue, I looked at the system log and I only see: Jan 23 20:57:42 marinosk com.apple.xpc.launchd[1] (raptor.Raptor.6008[885]): Service exited with abnormal code: 1

**Comment by sawhite** [comment]
I found that if you open a console/command window, navigate to the Applications directory, and then enter 
open ./Raptor.app
the application then launches. No idea why it doesn't launch in the normal way though...

**Comment by MarinosK** [comment]
after updating to 10.15.3 it works out of the box here

**Comment by sawhite** [comment]
I still have the same problem in MacOS 10.15.3. I checked the system log and I'm getting the same message that you had: com.apple.xpc.launchd[1] (raptor.Raptor.24740[48981]): Service exited with abnormal code: 1

**Comment by pendalino** [comment]
Thanks for all the suggestions above!

I have upgraded to 10.15.3 and reloaded Raptor but I still cannot start the Raptor program and 
I find the following in my system log:
error	23:44:02.214875-0600	Dock	Error processing AppleEvent, err=-1708

Apple Manager Error code -1708:
-1708 | The script doesn’t understand the <message> message. The event was not handled.
-- | --

If I try to start from the console window I get the following error message:
@MacBook-Pro /Applications % ./Raptor.app
zsh: permission denied: ./Raptor.app

**Comment by MarinosK** [comment]
I just updated to Java 8 update 241, and following that (and after a restart) Raptor will no longer launch once again.. I double click the icon, and Console gives five Messages in a row, as follows: 

`LAUNCHING:0x0-0x42042 Raptor foreground=1 bringForward=1 seed=125 userActivityCount=0`

`-[PersistentAppsSupport applicationReady:] | App: Raptor, ready, updating active tracking timer`

`-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Raptor`

`-[PersistentAppsSupport applicationQuit:] | for app:Raptor, _appTrackingState = 2`

`-[PersistentAppsSupport applicationQuit:] | App: Raptor, quit, updating active tracking timer`

**Comment by pendalino** [comment]
I have updated to Java 8 update 241 and cannot start Raptor. I don't get any messages. I haven't checked the system logs yet.

A friend has gone back to Mac OS X 10.14.6 to be able to get Raptor working again.

**Comment by carson-day** [comment]
Try this:
https://github.com/Raptor-Fics-Interface/Raptor/issues/81

**Comment by sawhite** [comment]
> Try this:
> #81

Thanks for the tip - it works for me :-)

**Comment by MarinosK** [comment]
Works here too - great.

**Comment by pendalino** [comment]
Thanks for the updates and posting the solution.
I haven't been able to accomplish this but I don't have a programming background.
Can anybody point me to some basic Mac programming sites to get me through this? The Mac help files are a bit vague and haven't gotten me through it.

I've got the terminal window open in the Raptor folder.
I'm using Nano editor for Raptor.app but there's no lines listed and I don't see anyway to delete the -d64 as instructed.
If I try to cut and paste the entire correct file, I can't seem to get it to take.

Any help would be appreciated. Thanks.

**Comment by MarinosK** [comment]
@pendalino 
- locate Raptor (probably in your Applications' folder)
- ctrl-click on it and select "Show Package Contents"
- find Contents/MacOs/Raptor file
- open it with some plain text editor, e.g. TextEdit (you could just drag 'n' drop the file on the TextEdit Application)
- delete the entire "-d64" line
- save
- that's it

**Comment by pendalino** [comment]
Thank you!

That got Raptor to start, but it opens into a blank window and I get the following error message:

Error occured! We are trying to make Raptor bug free and we need your help! Please take a moment to report this issue by selecting the menu:
  Help -> Report Issue 

Error in execute
NullPointerException: 
java.lang.NullPointerException
	at org.eclipse.swt.widgets.Control.internal_new_GC(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.graphics.GC.<init>(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.updateItems(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.updateItems(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder.onResize(Unknown Source)
	at org.eclipse.swt.custom.CTabFolder$1.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Control.resized(Unknown Source)
	at org.eclipse.swt.widgets.Composite.resized(Unknown Source)
	at org.eclipse.swt.widgets.Control.setFrameSize(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSView.setFrame(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.custom.SashFormLayout.layout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.updateLayout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.resized(Unknown Source)
	at org.eclipse.swt.widgets.Control.setFrameSize(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSView.setFrame(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.widgets.Control.setBounds(Unknown Source)
	at org.eclipse.swt.custom.SashFormLayout.layout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.updateLayout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.layout(Unknown Source)
	at org.eclipse.swt.widgets.Composite.layout(Unknown Source)
	at raptor.RaptorWindow$RaptorWindowSashForm.layout(RaptorWindow.java:527)
	at org.eclipse.swt.custom.SashForm.setMaximizedControl(Unknown Source)
	at raptor.RaptorWindow$RaptorWindowSashForm.restore(RaptorWindow.java:581)
	at raptor.RaptorWindow.restoreFolders(RaptorWindow.java:2283)
	at raptor.RaptorWindow$2.execute(RaptorWindow.java:699)
	at raptor.util.RaptorRunnable.run(RaptorRunnable.java:51)
	at org.eclipse.swt.widgets.RunnableLock.run(Unknown Source)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at raptor.Raptor.main(Raptor.java:214)
